r235 was incorrect as it assumed all parameters to finded could be passed individually to find. Instead of trying to be clever and strip / from parameters, just error out when parameters with trailing / are passed. The GUI should not pass these in any case.
git-svn-id: https://fslint.googlecode.com/svn/trunk@237 494acc53-a219-0410-adff-8f8ff343f446

diff --git a/fslint/finded b/fslint/finded
--- a/fslint/finded
+++ b/fslint/finded
@@ -43,10 +43,15 @@ done
 . "$script_dir"/supprt/getfpf -f "$argsToPassOn"
 #forcing -f as if specify an empty dir it would not display
 
+#flag trailing / as an error
+if printf "%s\n" "$@" | tr -s '/' | grep -q './$'; then
+    echo "Error: trailing '/' in a parameter is not allowed" >&2
+    exit 1
+fi
+
 (
 #get all dirs
 find "$@" -type d ! -name "*$LF*" -printf "$FPF\n" |
-sed 's#/$##' | #strip any trailing /
 sort -u #merge dirs (indirectly) specified multiple times
 
 #get all dirs containing files.
@@ -55,10 +60,7 @@ find "$@" ! -type d ! -name "*$LF*" -printf "%h\n" |
 uniq | #quick merge of dir names for each file
 sed -n ':s; p; s#/\{0,\}[^/]\{1,\}$##; /./b s' #separate dir nodes
 #Ensure we exclude parents to specified absolute dirs
-printf "%s\n" "$@" | sed 's#/$##' | #strip any trailing /
-while read path; do
-  find "$path" -maxdepth 0 ! -name "*$LF*" -printf "%h\n%h\n"
-done |
+find "$@" -maxdepth 0 ! -name "*$LF*" -printf "%h\n%h\n" |
 sed '/^\//!d' | #only process absolute dirs
 sed -n ':s; p; s#/\{0,\}[^/]\{1,\}$##; /./b s' #separate dir nodes
 ) |
