Add more robust checking that the python support scripts can be executed, rather than just being present
git-svn-id: https://fslint.googlecode.com/svn/trunk@38 494acc53-a219-0410-adff-8f8ff343f446

diff --git a/fslint/findup b/fslint/findup
--- a/fslint/findup
+++ b/fslint/findup
@@ -177,12 +177,12 @@ uniq --all-repeated=$sep_mode -w40 | #pick just duplicates
 if [ ! -z "$mode" ]; then
   cut -d' ' -f3- |
   if [ ! $mode = "gui" ]; then # external call to python as this is faster
-    if [ -f $script_dir/supprt/rmlint/fixdup.py ]; then
+    if $script_dir/supprt/rmlint/fixdup.py < /dev/null; then
         $script_dir/supprt/rmlint/fixdup.py $t$mode
-    elif [ -f $script_dir/supprt/rmlint/fixdup.sh ]; then
+    elif $script_dir/supprt/rmlint/fixdup.sh < /dev/null; then
         $script_dir/supprt/rmlint/fixdup.sh $t$mode
     else
-        echo "Error, couldn't find merge util" >&2
+        echo "Error, couldn't execute merge util" >&2
         exit 1
     fi
   else
